<start>       ::== <expression>

<expression>  ::== <expr-paren> | <expr-binary> | NUMBER

<expr-paren>  ::== "(" <expression> ")"
<expr-binary> ::== <expression> <binary> <expression>
<binary>      ::== "+" | "-" | "*" | "/" | "^"
